export const matchProofAbi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1" },
      { name: "name", type: "string" },
      { name: "version", type: "string" },
      { name: "chainId", type: "uint256" },
      { name: "verifyingContract", type: "address" },
      { name: "salt", type: "bytes32" },
      { name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDigest",
    inputs: [
      {
        name: "result",
        type: "tuple",
        components: [
          { name: "matchId", type: "bytes32" },
          { name: "winner", type: "address" },
          { name: "loser", type: "address" },
          { name: "gameId", type: "string" },
          { name: "winnerScore", type: "uint8" },
          { name: "loserScore", type: "uint8" },
          { name: "replayHash", type: "bytes32" },
          { name: "timestamp", type: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMatch",
    inputs: [{ name: "matchId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "matchId", type: "bytes32" },
          { name: "winner", type: "address" },
          { name: "loser", type: "address" },
          { name: "gameId", type: "string" },
          { name: "winnerScore", type: "uint8" },
          { name: "loserScore", type: "uint8" },
          { name: "replayHash", type: "bytes32" },
          { name: "timestamp", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMatchesByAgent",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recordMatch",
    inputs: [
      {
        name: "result",
        type: "tuple",
        components: [
          { name: "matchId", type: "bytes32" },
          { name: "winner", type: "address" },
          { name: "loser", type: "address" },
          { name: "gameId", type: "string" },
          { name: "winnerScore", type: "uint8" },
          { name: "loserScore", type: "uint8" },
          { name: "replayHash", type: "bytes32" },
          { name: "timestamp", type: "uint256" },
        ],
      },
      { name: "sigA", type: "bytes" },
      { name: "sigB", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "recorded",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "EIP712DomainChanged",
    inputs: [],
  },
  {
    type: "event",
    name: "MatchRecorded",
    inputs: [
      { name: "matchId", type: "bytes32", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "loser", type: "address", indexed: true },
      { name: "gameId", type: "string", indexed: false },
      { name: "winnerScore", type: "uint8", indexed: false },
      { name: "loserScore", type: "uint8", indexed: false },
      { name: "replayHash", type: "bytes32", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
] as const;
